[package]
name = "async-scope"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic-waker = "1.1.2"
futures-channel = "0.3.30"
pin-project-lite = "0.2.13"
slotmap = "1.0.7"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
