name: actionlint
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*.yml
  pull_request:
    paths:
      - .github/workflows/*.yml

jobs:
  lint:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/actionlint
