name: actionlint
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*.yml
  pull_request:
    paths:
      - .github/workflows/*.yml

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install actionlint
        run: bash <(curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Run actionlint
        run: |
          ./actionlint                                                    \
            -format "$(cat .github/data/actionlint-sarif-template.txt)" \
            > actionlint.sarif

      - uses: actions/upload-artifact@v4
        with:
          name: actionlint-sarif
          path: actionlint.sarif

  upload:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - lint
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: actionlint-sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: actionlint.sarif
